// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dag.proto

/*
Package dag is a generated protocol buffer package.

It is generated from these files:
	dag.proto

It has these top-level messages:
	Step
	Event
*/
package dag

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EventType int32

const (
	EventType_UNKNOWN  EventType = 0
	EventType_NEW      EventType = 1
	EventType_READY    EventType = 2
	EventType_RUNNING  EventType = 3
	EventType_SUCCESS  EventType = 4
	EventType_FAILURE  EventType = 5
	EventType_CANCELED EventType = 6
	EventType_CLOSE    EventType = 7
)

var EventType_name = map[int32]string{
	0: "UNKNOWN",
	1: "NEW",
	2: "READY",
	3: "RUNNING",
	4: "SUCCESS",
	5: "FAILURE",
	6: "CANCELED",
	7: "CLOSE",
}
var EventType_value = map[string]int32{
	"UNKNOWN":  0,
	"NEW":      1,
	"READY":    2,
	"RUNNING":  3,
	"SUCCESS":  4,
	"FAILURE":  5,
	"CANCELED": 6,
	"CLOSE":    7,
}

func (x EventType) String() string {
	return proto.EnumName(EventType_name, int32(x))
}
func (EventType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Step struct {
	StepId  string   `protobuf:"bytes,1,opt,name=step_id,json=stepId" json:"step_id,omitempty"`
	Depends []string `protobuf:"bytes,2,rep,name=depends" json:"depends,omitempty"`
}

func (m *Step) Reset()                    { *m = Step{} }
func (m *Step) String() string            { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()               {}
func (*Step) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Step) GetStepId() string {
	if m != nil {
		return m.StepId
	}
	return ""
}

func (m *Step) GetDepends() []string {
	if m != nil {
		return m.Depends
	}
	return nil
}

type Event struct {
	StepId  string    `protobuf:"bytes,1,opt,name=step_id,json=stepId" json:"step_id,omitempty"`
	Event   EventType `protobuf:"varint,2,opt,name=event,enum=dag.EventType" json:"event,omitempty"`
	Depends []string  `protobuf:"bytes,3,rep,name=depends" json:"depends,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Event) GetStepId() string {
	if m != nil {
		return m.StepId
	}
	return ""
}

func (m *Event) GetEvent() EventType {
	if m != nil {
		return m.Event
	}
	return EventType_UNKNOWN
}

func (m *Event) GetDepends() []string {
	if m != nil {
		return m.Depends
	}
	return nil
}

func init() {
	proto.RegisterType((*Step)(nil), "dag.Step")
	proto.RegisterType((*Event)(nil), "dag.Event")
	proto.RegisterEnum("dag.EventType", EventType_name, EventType_value)
}

func init() { proto.RegisterFile("dag.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0x87, 0x6d, 0xb3, 0x36, 0xe6, 0x29, 0xe3, 0x91, 0x8b, 0x3d, 0x96, 0xe1, 0xa1, 0x78, 0xd8,
	0x41, 0x4f, 0x1e, 0x4b, 0xf6, 0x94, 0x62, 0x79, 0x83, 0xc4, 0x32, 0x3c, 0xe9, 0x24, 0x61, 0x08,
	0xb2, 0x05, 0x57, 0x04, 0xff, 0x7b, 0xc9, 0x44, 0xd1, 0x83, 0xc7, 0x8f, 0xf7, 0xfb, 0xf8, 0xe0,
	0x81, 0xf2, 0xeb, 0xcd, 0x3c, 0xbe, 0xed, 0xc6, 0x9d, 0x16, 0x7e, 0xbd, 0x99, 0x5d, 0xc3, 0xc4,
	0x8d, 0x21, 0xea, 0x33, 0x90, 0xfb, 0x31, 0xc4, 0xc7, 0x17, 0x5f, 0x65, 0x75, 0xd6, 0x28, 0x5b,
	0x26, 0xec, 0xbc, 0xae, 0x40, 0xfa, 0x10, 0xc3, 0xd6, 0xef, 0xab, 0xbc, 0x16, 0x8d, 0xb2, 0xdf,
	0x38, 0x7b, 0x82, 0x82, 0xde, 0xc3, 0x76, 0xfc, 0xdf, 0x3d, 0x87, 0x22, 0xa4, 0x45, 0x95, 0xd7,
	0x59, 0x33, 0xbd, 0x9c, 0xce, 0x53, 0xfc, 0xe0, 0xdc, 0x7f, 0xc4, 0x60, 0xbf, 0x8e, 0xbf, 0x0b,
	0xe2, 0x4f, 0xe1, 0xe2, 0x15, 0xd4, 0xcf, 0x5a, 0x9f, 0x80, 0x1c, 0xf8, 0x8e, 0x97, 0x2b, 0xc6,
	0x23, 0x2d, 0x41, 0x30, 0xad, 0x30, 0xd3, 0x0a, 0x0a, 0x4b, 0xed, 0xe2, 0x01, 0xf3, 0x34, 0xb0,
	0x03, 0x73, 0xc7, 0xb7, 0x28, 0x12, 0xb8, 0xc1, 0x18, 0x72, 0x0e, 0x27, 0x09, 0x6e, 0xda, 0xae,
	0x1f, 0x2c, 0x61, 0xa1, 0x4f, 0xe1, 0xd8, 0xb4, 0x6c, 0xa8, 0xa7, 0x05, 0x96, 0xc9, 0x37, 0xfd,
	0xd2, 0x11, 0xca, 0xe7, 0xf2, 0xf0, 0x96, 0xab, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x07,
	0x58, 0xc7, 0x23, 0x01, 0x00, 0x00,
}
