// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dag.proto

/*
Package dag is a generated protocol buffer package.

It is generated from these files:
	dag.proto

It has these top-level messages:
	Step
*/
package dag

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Step struct {
	DagId  string   `protobuf:"bytes,1,opt,name=dag_id,json=dagId" json:"dag_id,omitempty"`
	StepId string   `protobuf:"bytes,2,opt,name=step_id,json=stepId" json:"step_id,omitempty"`
	Parent []string `protobuf:"bytes,3,rep,name=parent" json:"parent,omitempty"`
}

func (m *Step) Reset()                    { *m = Step{} }
func (m *Step) String() string            { return proto.CompactTextString(m) }
func (*Step) ProtoMessage()               {}
func (*Step) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Step) GetDagId() string {
	if m != nil {
		return m.DagId
	}
	return ""
}

func (m *Step) GetStepId() string {
	if m != nil {
		return m.StepId
	}
	return ""
}

func (m *Step) GetParent() []string {
	if m != nil {
		return m.Parent
	}
	return nil
}

func init() {
	proto.RegisterType((*Step)(nil), "dag.Step")
}

func init() { proto.RegisterFile("dag.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 111 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4c, 0x49, 0x4c, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x4e, 0x49, 0x4c, 0x57, 0xf2, 0xe3, 0x62, 0x09, 0x2e,
	0x49, 0x2d, 0x10, 0x12, 0xe5, 0x62, 0x4b, 0x49, 0x4c, 0x8f, 0xcf, 0x4c, 0x91, 0x60, 0x54, 0x60,
	0xd4, 0xe0, 0x0c, 0x62, 0x4d, 0x49, 0x4c, 0xf7, 0x4c, 0x11, 0x12, 0xe7, 0x62, 0x2f, 0x2e, 0x49,
	0x2d, 0x00, 0x89, 0x33, 0x81, 0xc5, 0xd9, 0x40, 0x5c, 0xcf, 0x14, 0x21, 0x31, 0x2e, 0xb6, 0x82,
	0xc4, 0xa2, 0xd4, 0xbc, 0x12, 0x09, 0x66, 0x05, 0x66, 0x90, 0x38, 0x84, 0x97, 0xc4, 0x06, 0x36,
	0xdb, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x3e, 0xe6, 0xa9, 0x4e, 0x68, 0x00, 0x00, 0x00,
}
